"""change in invoice

Revision ID: bfdecd6e24b0
Revises: 3f4308122b13
Create Date: 2024-10-04 12:24:33.559032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdecd6e24b0'
down_revision: Union[str, None] = '3f4308122b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
