"""v 2 change the invoice table 

Revision ID: 3f4308122b13
Revises: 904c60fb3e6f
Create Date: 2024-09-13 15:26:17.834460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4308122b13'
down_revision: Union[str, None] = '904c60fb3e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('overdue_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'overdue_date')
    # ### end Alembic commands ###
